### ISSUE TITLE
Add type = module to the .info file

### ISSUE THREAD

**Issue by quicksketch** [backdrop-contrib/markdown#1]
The packager on BackdropCMS.org requires that you have a line in your .info file to identify what kind of project it is (as themes, modules, and layouts are all mashed together here in the backdrop-contrib group).

It's also required for the Backdrop installer to install a remote module from a .zip file, as of 1.2.0. See https://github.com/backdrop/backdrop-issues/issues/1215.

To fix this, just add:

```
type = module
```

To the .info file.

p.s. And it would be great to make an official release as well so it shows up on BackdropCMS.org. :smile:

**Comment by herbdool** [comment]
I've added type = module. If you're okay @chrisherberte I can create a tag for an official release, unless you want to do it.

**Comment by ghost** [comment]
hi Herb, please go ahead create new release thank you

_Chris Herberte_ // [07] 40938716 // 0449 002 700
