### ISSUE TITLE
Fatal error on "Declaration must be compatible"

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/markdown#13]
I had to disable this module because of a fatal error. I haven't checked whether this is because I am using php > 7.4 or not. This is the error message:

```
Declaration of Michelf\Markdown::defaultTransform($text) must be compatible with Michelf\MarkdownInterface::defaultTransform(string $text):
```

I could fix it by changing the markdown files within in the includes folder for the ones found here: https://github.com/michelf/php-markdown/tree/lib/Michelf

**Comment by bugfolder** [comment]
I've been using it with PHP 8.1 with no issues. Any idea on what's triggering the error for you?

I did a diff of the current library against the latest HEAD on [https://github.com/michelf/php-markdown](https://github.com/michelf/php-markdown), and there's a few changes in MarkdownExtra.php. It would probably make sense to upgrade to the latest HEAD if it fixes the issue for you, but it would be nice to know exactly what triggers it.

**Comment by robertgarrigos** [comment]
Sorry, @bugfolder, I don't know what caused the error. Updating the library fixed it, indeed.

**Comment by bugfolder** [comment]
OK, I'll do some testing and then update the library.

**Comment by bugfolder** [comment]
I've updated the library in a new release.
