### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/markdown#9]
Per the discussion in https://github.com/backdrop-contrib/markdown/issues/4 (and following the guidelines of https://docs.backdropcms.org/documentation/adopt-a-project), I'm asking the maintainers: are they still interested in maintaining the project?

I'd be happy to become a (co)-maintainer of this module (which I like a lot).

**Comment by alanmels** [comment]
When you take over the module, please see new PR https://github.com/backdrop-contrib/markdown/pull/10/files

**Comment by bugfolder** [comment]
> When you take over the module, please see new PR

Noted. The statutory waiting time is 2 weeks, so if I don't hear anything by Dec 13, I'll take it over then.

**Comment by alanmels** [comment]
For a module untouched for years, two weeks of mandatory waiting is a bit of overkill. Backdrop community needs to improve some of its procedures IMO.

**Comment by stpaultim** [comment]
@alanmels - I don't think anyone would dispute that some of our procedues could use improvement. The challenge is coming up with and implementing new procedures. 

We have a process for re-assigning mantainership of modules that is pretty clear and hasn't led to any disputes that I'm aware of. Although, it does at times seem a bit slower than ideal (I agree on that point). How would you change the process in a way that is clean, fair, easy to manage, and not likely to offend existing contrib maintainers?

If you have a proposal, I'll make sure it get's consideration.

**Comment by alanmels** [comment]
@stpaultim, I would keep the same two weeks period if a module was somehow updated at least within last 12 months to give the current maintainer(s) a chance to respond. However, if it was not touched for years then it definitely means it has been already abandoned long time ago. 

Backdrop needs to be agile enough to develop more efficiently, so some formalities like this don't need to turn into completely unnecessary bureaucracy (and we all know very well, these two weeks are bureaucracy). It's not like a new maintainer would mind if somehow the old one(s) suddenly popped up again to re-join the team or take it back. 

As I see it, Backdrop contributed modules are not personal properties of their maintainers, it's more of responsibility which require time, attention and care. So quickly adding a new maintainer to modules which seem abandoned long time ago would not hurt anyone. Don't take off the old ones, but add a new one if someone is willing to spend some efforts on anything. It simply is not productive to keep blockers for a new energy in environment of deficiency of developers and maintainers.
